### ISSUE TITLE
@alwx plz rebase

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/frappe#8]
@alwx Can you please rebase all of your commits into one?  And give a detailed log in one commit?  Otherwise I need to rebase it myself.  Also you did something to the Readme and the animated demo gif is gone, it's now a PNG or something and it doesn't load (you aren't using RawGit anymore).  It's just too hard to go through the ten or so commits

**Comment by alwx** [comment]
Will do it later today.

**Comment by alwx** [comment]
There is a commit by @skevy between my commits, that's why I decided to squash my commits separately. But I hope git log looks much better now, and I am sorry for adding lots of stupid commit messages :)

Moved image to RawGit. I think that this new image gives people more information about how this application work, that's why I replaced old gif by this one. But if you don't agree, you can move your image back. It is your repo, and I am kinda guest here :)

**Comment by skevy** [comment]
@alwx should there be a 0.1.2 release after you cleaned up commits? or is all the code the same as 0.1.1?

**Comment by alwx** [comment]
All the code is still the same. That's why I don't think that we need to create one more release.
