### ISSUE TITLE
why does it not work with my HM note2 phone ?

### ISSUE THREAD

**Issue by tom31203120** [niftylettuce/frappe#9]
when I shake or reloadJs , only awake menu.

**Comment by alwx** [comment]
Do you have adb installed?
Frappé requires Android Debug Bridge to be installed and added to your $PATH. Adb is included to Android SDK, and you can download it here: http://developer.android.com/intl/ru/sdk/index.html#Other

You should also add these 2 lines to your .bash_profile or .zshrc or whatever:
```
export ANDROID_HOME=/Users/<your user>/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
```

**Comment by tom31203120** [comment]
ADB works fine or I can't `shake` .
But `ReloadJs` menu does not show, only system menu prompt .

**Comment by alwx** [comment]
Don't know. 
Most probably your device's manufacturer has its own opinion on how "Menu" button should work (actually, we're just simulating menu button press instead of "shaking"), and overrides default React Native behaviour (do you use React Native, right? because the main purpose of Frappé is to work with React Native debug menu remotely).

**Comment by tom31203120** [comment]
Yeah, I use React Native. 
I got it , you just simulating menu button press, not shaking a phone.
I wonder if you are going to support remotely shaking the phone device in the future ? 
Thank you very much , and I will donate then :)

**Comment by alwx** [comment]
It is not possible to simulate shaking, unfortunately.
